[package]
name = "game_components_minigame"
version.workspace = true
edition.workspace = true

[lib]

[cairo]
sierra-replace-ids = true

[dependencies]
starknet.workspace = true
game_components_metagame = { path = "../metagame" }
game_components_token = { path = "../token" }
game_components_utils = { path = "../utils" }
openzeppelin_token = "2.0.0"
openzeppelin_introspection = "2.0.0"

[dev-dependencies]
snforge_std = "0.45.0"
