[package]
name = "game_components_token"
version = "1.5.1"
edition = "2024_07"
cairo-version = "=2.12.1"

[dependencies]
starknet = "2.12.1"
openzeppelin_token = "2.0.0"
openzeppelin_introspection = "2.0.0"
# Game components dependencies
game_components_minigame = { path = "../minigame" }
game_components_metagame = { path = "../metagame" }
game_components_utils = { path = "../utils" }
game_components_test_starknet = { path = "../test_starknet" }

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true


[lib]